In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
data = {'YearsExperience': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
        'Salary': [50000, 60000, 70000, 80000, 90000, 100000, 110000, 120000, 130000, 140000]}
df = pd.DataFrame(data)
x = df.iloc[:, 0:1].values
y = df.iloc[:, 1].values
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)
print("x_train:\n", x_train)
print("y_train:\n", y_train)
print("x_test:\n", x_test)
print("y_test:\n", y_test)
regressor = LinearRegression()
regressor.fit(x_train, y_train)
print("Coefficients:", regressor.coef_)
print("Intercept:", regressor.intercept_)


x_train:
 [[10]
 [ 2]
 [ 7]
 [ 8]
 [ 4]
 [ 1]
 [ 6]]
y_train:
 [140000  60000 110000 120000  80000  50000 100000]
x_test:
 [[3]
 [9]
 [5]]
y_test:
 [ 70000 130000  90000]
Coefficients: [10000.]
Intercept: 40000.00000000002
