In [25]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
data = {'Position': ['CEO', 'charman', 'director', 'Senior Manager', 'Junior Manager', 'Intern'], 
        'Level': [1, 2, 3, 4, 5, 6], 
        'Salary': [50000, 80000, 110000, 150000, 200000, 250000]}
df = pd.DataFrame(data)
x = df.iloc[:, 1:2].values
y = df.iloc[:, 2].values
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)
print("x_train:\n", x_train)
print("y_train:\n", y_train)
print("x_test:\n", x_test)
print("y_test:\n", y_test)
regressor = LinearRegression()
regressor.fit(x_train, y_train)

# Print the coefficients and intercept
print("Coefficients:", regressor.coef_)
print("Intercept:", regressor.intercept_)


x_train:
 [[2]
 [4]
 [1]
 [5]]
y_train:
 [ 80000 150000  50000 200000]
x_test:
 [[6]
 [3]]
y_test:
 [250000 110000]
Coefficients: [37000.]
Intercept: 9000.0
